global:
  domain: example.com
  clusterServer: https://kubernetes.default.svc
  argocdNamespace: argocd
  targetRevision: HEAD
  useLocalGit: false
  remoteGitRepo: "git@github.com:example/cluster.git"
  localGitRepo:  "git@gitea.{{ .Values.global.domain }}:example/cluster.git"
  repoBasePath: examples/consumer

apps:
  hello: true
